server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/realtime?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*Dao.xml
  typeAliasesPackage: com.realtime.**.entity
#
#spring:
#  profiles:
#    active: dev
#
#---
#server:
#  port: 8083
#
#spring:
#  config:
#    activate:
#      on-profile: dev
#
#
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/realtime?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#    username: root
#    password: 123456
#
#mybatis:
#  mapper-locations: classpath:mapper/*Dao.xml
#  typeAliasesPackage: com.realtime.**.entity
#
#---
#server:
#  port: 8084
#
#spring:
#  profiles:
#    active: test
#
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/realtime?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#    username: root
#    password: 123456
#
#mybatis:
#  mapper-locations: classpath:mapper/*Dao.xml
#  typeAliasesPackage: com.realtime.**.entity
#
#
#---
#server:
#  port: 8085
#
#spring:
#  profiles:
#    active: prod
#
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/realtime?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#    username: root
#    password: 123456
#
#mybatis:
#  mapper-locations: classpath:mapper/*Dao.xml
#  typeAliasesPackage: com.realtime.**.entity